name: CI Labeled Test
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Show context
        env:
          LABEL_NAME: ${{ github.event.label.name }}
        run: echo "$LABEL_NAME"
