name: CI Medium Test
on:
  push:
    branches:
      - 'features/**'

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Echo the greeting's time
        run: echo 'This is a medium test.'
